### ISSUE TITLE
Graph on the statistics page doesnt work

### ISSUE THREAD

**Issue by bhsi-snm** [NHMDenmark/DaSSCo-asset-service#102]
# Template for isues/tickets
##  What is the issue ?
The graph and functionality of downloading assets and reports are not available currently 

```
# Detailed description of the issue. 
# It could include examples,reference to similar issue and clear boundaries of the issue.


```

## Why is it needed/relevant ?
```
# Explain the need, relevance.
# Give scenario(s) of why and when this could be relevant. 

```
## Estimate level of effort required.

```
# easy
# difficult
# hard

```

## What is the expected acceptable result.

```
#  How to approach it?
#  Give a clear approach/potential solution on how to resolve it.
#  What steps would be required to do this ?
#  It might also be an idea to put some pseudocode if relevant.

```

# What could be the challenges ? 

```
Is there a potential risk to this. 
Could it affect another part of the project. 
```

# What test are required ?

`New tests/Could include reference to the existing test`

# What documentation required?

`Could refer to existing documentation and changes in relevant doc files.`

# Remarks

**Comment by Grand666** [comment]
Hi @bhsi-snm and @PipBrewer,

Thomas has made a fix for the Statistic View, and it is back to be responsive. 

I've just deployed the changes and it seems to work just fine. :)

**Comment by Grand666** [comment]
After a talk with Bhupjit, it's clearly faster, but it seems there's still a few issues.

The graph does not seem to have the data for the past week, but also the buttons on the statistics view does not seem to work as intended.

Instead of 3 button we need 2, 1 to clear the custom date ranges and 1 force refresh the cache.

**Comment by Grand666** [comment]
The data seems to be correct, it is supposed to show specimens created not assets.

We will still take a look at the buttons.

**Comment by Baeist** [comment]
The numbers displayed doesnt seem to work for monthly/weekly fluctuations. Also the displayed numbers dont match up when looking at "total" and all time numbers. Could be due to scattered test data and when what was implemented, but makes it hard to tell if its actually displaying things correctly.

Would also want the graph part to have more space. Maybe put the number blocks to one side in a column or size them down. 

@bhsi-snm

**Comment by Baeist** [comment]
The graph itself looks good now.

The underlying numbers still dont quite add up. I dont think we have time for this currently since it may just be a mangled database causing this. 

@bhsi-snm

**Comment by bhsi-snm** [comment]
@Baeist can you write up the error specifically here, and we can get NT to give an estimate and probable cause

**Comment by Baeist** [comment]
If i find all assets in ARS through search queries the number adds up to something. That number doesnt match the number in the all time column on the stats page. There is 8200 assets from quering and 8197 in total. 

When you change the date range on the stats page to include everything the total shown for the date range doesnt match the all data column. There is one extra metadata received than in the total column.

edit: these numbers change daily also since its being tested.

**Comment by Grand666** [comment]
Right now I get around 8200 assets when querying using search: 

<img width="1573" height="290" alt="Image" src="https://github.com/user-attachments/assets/1f5a5082-beac-43e2-a167-81cb7f068798" />

when I look in the stats page I have: 

<img width="272" height="603" alt="Image" src="https://github.com/user-attachments/assets/3b23203e-b58e-44fb-8372-7ecdc88def95" />

Which is 8200. Am I looking in the wrong stats?


Remember there is a cache on the stats view, but a "reset cache" button if you want to force a reload.

**Comment by Baeist** [comment]
Yes i also get everything to match up now.
